GET http://localhost:3001/api/joke

###
POST  https://reqres.in/api/users
Content-Type: application/json

{
    "name": "morpheus",
    "job": "leader"
}

###
POST http://localhost:3001/api/create-user
Content-Type: application/json

{
    "name": "Bill",
    "occupation": "Gardener"
}